on:
  push:
    paths:
      - README.Rmd

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: |
          install.packages("rmarkdown")
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Install package
        run: R CMD INSTALL .
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "github_document")'
      - name: Commit results
        run: |
          git add README.md && git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push https://$:$@github.com/$.git HEAD:$ || echo "No changes to commit"





